const imageByName = (filename) => `/media/gallery/${filename}`;

const codebnGallery = [
  {
    slug: "codebn-wrc-track",
    src: "/media/codebn/wrc7.webp",
    title: "赛事训练体系",
    category: "竞赛成果",
    description: "官网赛事素材补充了机器人竞赛和长期训练的完整场景。",
  },
  {
    slug: "codebn-python-course",
    src: "/media/codebn/python-course.webp",
    title: "Python 课程入口",
    category: "项目展示",
    description: "课程体系和真实课堂结合，让编程学习更容易被家长理解。",
  },
  {
    slug: "codebn-cpp-course",
    src: "/media/codebn/cpp-course.webp",
    title: "C++ 竞赛路线",
    category: "项目展示",
    description: "C++ 和信息学路径对应更系统的算法训练与竞赛准备。",
  },
  {
    slug: "codebn-robot-detail",
    src: "/media/codebn/robot-detail1.webp",
    title: "机器人项目细节",
    category: "项目展示",
    description: "机器人项目把结构、控制、调试和展示连接成完整实践。",
  },
  {
    slug: "codebn-robot-lab",
    src: "/media/codebn/robot-detail2.webp",
    title: "机器人课堂场景",
    category: "教学现场",
    description: "机器人课堂让学生在真实装置和任务中理解编程逻辑。",
  },
  {
    slug: "codebn-activity-camp",
    src: "/media/codebn/camp2.webp",
    title: "活动营地现场",
    category: "活动出行",
    description: "活动和营地让学习从教室延展到更丰富的成长体验。",
  },
];

const curatedGallery = [
  {
    slug: "classroom-guidance",
    filename: "4e7cde1d67137f31dbbaceea09b3ba97.jpg",
    title: "课堂辅导时刻",
    category: "教学现场",
    description: "围在电脑前拆问题，把抽象思路讲成学生能马上动手的步骤。",
  },
  {
    slug: "teacher-student-portrait",
    filename: "03e58ed3352bb2c5b6c34475e3ef5c05.jpg",
    title: "师生同框",
    category: "师生合影",
    description: "真实陪伴带来的安全感，会影响学生是否愿意继续表达和尝试。",
  },
  {
    slug: "student-group-energy",
    filename: "145fb7106917a5e7c056478f657577c6.jpg",
    title: "课堂展示氛围",
    category: "学生团队",
    description: "作品展示后的兴奋和表达欲，是课堂气氛被点亮的信号。",
  },
  {
    slug: "wrcc-stage-portrait",
    filename: "415738909ed8cf9eb1594535c8e3537e.jpg",
    title: "WRCC 领奖留影",
    category: "竞赛成果",
    description: "站上正式赛场之后，学生会更清楚项目训练最终能落到什么样的结果。",
  },
  {
    slug: "wrcc-team-banner",
    filename: "4c034334db22d80ecae7cd665b142e62.jpg",
    title: "团队展板合影",
    category: "竞赛成果",
    description: "团队照把项目成果、现场气氛和集体归属感合在一起。",
  },
  {
    slug: "classroom-brothers",
    filename: "5532032ec1ecd25b5aab600c3c66653e.jpg",
    title: "教室里的团队站位",
    category: "学生团队",
    description: "不同年龄段学生一起成长时，团队氛围会自然把新生也带起来。",
  },
  {
    slug: "wrcc-yichang-award",
    filename: "57b76a27feb1167ff4387a3bcb517eae.jpg",
    title: "WRCC 宜昌领奖台",
    category: "竞赛成果",
    description: "从平时训练到领奖时刻，学生能看见自己的投入最终长成了什么样子。",
  },
  {
    slug: "wrcc-beijing-team",
    filename: "6e43b26aa8d461efbe6bfd108898c4bf.jpg",
    title: "北京锦标赛团队照",
    category: "竞赛成果",
    description: "大型赛事现场也是长期训练、项目执行和舞台表达能力的集中呈现。",
  },
  {
    slug: "window-team",
    filename: "7274f1e1f018e70e0e0b5f17d360949e.jpg",
    title: "窗边学生团队",
    category: "学生团队",
    description: "不同阶段的学生一起学习时，团队氛围会把新生也带进来。",
  },
  {
    slug: "great-wall-outing",
    filename: "7b0629ffd37a15672eabce6da7b6563c.jpg",
    title: "长城活动日",
    category: "活动出行",
    description: "学习之外的同行与出行，会让师生关系更真实，也更持久。",
  },
  {
    slug: "project-photo-wall",
    filename: "7ea7aec2c2fc24cdff315baf30e19994.jpg",
    title: "作品墙前合影",
    category: "教学现场",
    description: "当作品能被公开展示，学生对项目的投入会明显提升。",
  },
  {
    slug: "python-adventure-stage",
    filename: "821a0144bad69f633441e1e7f00b0e20.jpg",
    title: "Python 冒险岛现场分享",
    category: "项目展示",
    description: "把应用项目讲给更多人听，本身就是一次教学和表达训练。",
  },
  {
    slug: "teacher-student-medal",
    filename: "85fa5f3cea36d06b89a2802a08dd6d3a.jpg",
    title: "获奖后合影",
    category: "师生合影",
    description: "成果落地的那一刻，也是长期投入最能建立信任的时刻。",
  },
  {
    slug: "robot-competition-team",
    filename: "9f553117006eb7273508fce3e103dc84.jpg",
    title: "赛场团队展示",
    category: "竞赛成果",
    description: "大型活动现场把训练成果和舞台表达能力一起放大出来。",
  },
  {
    slug: "competition-floor",
    filename: "b28454710e48410eece89976a37892f6.jpg",
    title: "比赛执行现场",
    category: "竞赛成果",
    description: "从讲解到调试再到现场执行，训练价值往往体现在这些细节里。",
  },
  {
    slug: "debugging-scene",
    filename: "bf42704d89c36b8f7175792f2c6406df.jpg",
    title: "赛中调试时刻",
    category: "竞赛成果",
    description: "问题解决能力通常发生在临场调试和快速判断的瞬间。",
  },
  {
    slug: "certificate-group",
    filename: "c96b1c78e290ab5926348141528de895.jpg",
    title: "证书合影",
    category: "学生团队",
    description: "证书不是终点，但会给学生一个很强的确认感。",
  },
  {
    slug: "celebration-class",
    filename: "ca5c3b9bbe952a3346d5352649d7c360.jpg",
    title: "课堂成果庆祝",
    category: "学生团队",
    description: "把成果举起来分享的那一刻，会自然形成下一轮学习动力。",
  },
  {
    slug: "daily-portrait",
    filename: "d192b171f4334ba3f7d1987d8cd29b5e.jpg",
    title: "日常课堂自拍",
    category: "教学现场",
    description: "稳定的课堂陪伴，是长期学习效果里最重要的部分之一。",
  },
  {
    slug: "small-award-photo",
    filename: "dd3021a727e24d95c138b1f8e91c8d66.jpg",
    title: "小小成果时刻",
    category: "师生合影",
    description: "每一次小成果都值得被记录，因为它们会把自信慢慢堆起来。",
  },
  {
    slug: "certificate-selfie",
    filename: "ebd6de98caacf995a5fc46d55623341d.jpg",
    title: "证书自拍现场",
    category: "教学现场",
    description: "老师和学生一起拿到成果时，成就感会变成集体记忆。",
  },
  {
    slug: "classroom-crew",
    filename: "ebe3db8e9e230e42fa4a3821dc906ca8.jpg",
    title: "日常学习小队",
    category: "学生团队",
    description: "团队学习让学生更自然地进入表达、合作和互相带动。",
  },
  {
    slug: "mentor-checkpoint",
    filename: "efe82287a2ef87a865246b17efb2cb5a.jpg",
    title: "阶段性陪伴合影",
    category: "师生合影",
    description: "每个阶段的合影都像一个检查点，记录已经走过的真实路径。",
  },
];

export const GALLERY_ITEMS = [
  ...curatedGallery.map((item) => ({
    ...item,
    src: imageByName(item.filename),
  })),
  ...codebnGallery,
];
