export const STAGE_APPS = [
  {
    id: "python-adventure",
    name: "Python 冒险岛",
    href: "https://game.codebn.cn/",
    screenshot: "/media/captures/python-adventure.png",
    category: "游戏化编程",
    kicker: "Flagship Learning Product",
    description: "闯关、任务与即时反馈，把 Python 入门做成可体验的学习产品。",
    highlights: ["地图闯关", "代码即时反馈", "作品型课堂入口"],
    accent: "cyan",
    posterTitle: "Adventure Engine",
    posterSubtitle: "Quest / Logic / Python",
    posterStats: ["6+ 学习阶段", "实时闯关反馈", "公开展示入口"],
  },
  {
    id: "classroom-feedback",
    name: "课堂反馈系统",
    href: "https://stu.codebn.cn/",
    screenshot: "/media/captures/classroom-feedback.png",
    category: "教学服务闭环",
    kicker: "Feedback & Growth Loop",
    description: "课堂记录、家校沟通和成长反馈连成一个可追踪的服务闭环。",
    highlights: ["课堂反馈闭环", "小程序触达", "家校沟通更及时"],
    accent: "amber",
    posterTitle: "Class Feedback Loop",
    posterSubtitle: "Lesson / Family / Growth",
    posterStats: ["记录可视化", "移动端查看", "服务体验升级"],
  },
];

export const APP_SHOWCASE_ITEMS = [
  {
    id: "python-adventure",
    name: "Python 冒险岛",
    href: "https://game.codebn.cn/",
    screenshot: "/media/captures/python-adventure.png",
    category: "游戏化编程",
    summary: "主舞台旗舰项目，把课堂体验做成可直接演示的互动应用。",
    palette: "cyan",
    poster: {
      eyebrow: "CORE RELEASE",
      title: "Python Adventure Island",
      subtitle: "Quest / Script / Stage Demo",
      metrics: ["地图闯关", "项目式学习", "展示转化"],
    },
  },
  {
    id: "typing-fun",
    name: "乐享课堂",
    href: "https://class.codebn.cn/",
    screenshot: "/media/captures/typing-fun.png",
    category: "课堂应用矩阵",
    summary: "把编程、AI、仿真和课堂工具放在同一个入口里，适合公开展示和课堂使用。",
    palette: "teal",
    poster: {
      eyebrow: "CLASS SUITE",
      title: "Learning App Hub",
      subtitle: "Class / AI / Tools",
      metrics: ["课堂中心", "应用入口", "综合展示"],
    },
  },
  {
    id: "ai-research",
    name: "AI Research",
    href: "https://ai.codebn.cn/",
    screenshot: "/media/captures/ai-research.png",
    category: "AI 探索",
    summary: "聚焦 AI 工具理解、研究体验和内容拓展，让课堂更接近真实前沿。",
    palette: "violet",
    poster: {
      eyebrow: "AI LAB",
      title: "AI Research",
      subtitle: "Search / Reason / Explore",
      metrics: ["AI 应用理解", "研究式学习", "主题延展"],
    },
  },
  {
    id: "code-research",
    name: "Code Research",
    href: "https://class.codebn.cn/",
    screenshot: "/media/captures/typing-fun.png",
    category: "代码研究",
    summary: "通过案例拆解和代码阅读，帮助学生把会写升级成会看、会改、会讲。",
    palette: "blue",
    poster: {
      eyebrow: "CODE STUDY",
      title: "Code Research",
      subtitle: "Read / Debug / Explain",
      metrics: ["代码拆解", "案例学习", "表达联动"],
    },
  },
  {
    id: "interactive-classroom",
    name: "AI 互动课堂",
    href: "https://ai.codebn.cn/",
    screenshot: "/media/captures/ai-research.png",
    category: "互动生成",
    summary: "面向课堂即兴提问和主题生成，让讲解更有现场感和参与感。",
    palette: "pink",
    poster: {
      eyebrow: "LIVE CLASS",
      title: "AI Interactive Classroom",
      subtitle: "Prompt / Generate / Engage",
      metrics: ["互动生成", "课堂参与", "主题扩展"],
    },
  },
  {
    id: "model-training",
    name: "模型训练",
    href: "https://class.codebn.cn/",
    screenshot: "/media/captures/typing-fun.png",
    category: "AI 实验",
    summary: "把样本、训练和结果反馈做成可体验内容，帮助学生理解模型思维。",
    palette: "lime",
    poster: {
      eyebrow: "TRAINING LOOP",
      title: "Model Training",
      subtitle: "Sample / Train / Result",
      metrics: ["样本意识", "模型反馈", "实验体验"],
    },
  },
  {
    id: "simulation",
    name: "仿真模拟",
    href: "https://class.codebn.cn/",
    screenshot: "/media/captures/typing-fun.png",
    category: "科学交互",
    summary: "把抽象科学概念转换为可拖拽、可调参、可观察的仿真实验界面。",
    palette: "indigo",
    poster: {
      eyebrow: "SIMULATION LAB",
      title: "Simulation",
      subtitle: "Observe / Tweak / Learn",
      metrics: ["科学可视化", "调参与观察", "课程联动"],
    },
  },
  {
    id: "classroom-feedback",
    name: "课堂反馈系统",
    railName: "课堂反馈 / 小程序",
    href: "https://stu.codebn.cn/",
    screenshot: "/media/captures/classroom-feedback.png",
    category: "教学服务",
    summary: "连接课堂评价、小程序触达和成长记录，是教学闭环里的第二核心入口。",
    palette: "amber",
    poster: {
      eyebrow: "SERVICE LOOP",
      title: "Classroom Feedback",
      subtitle: "Track / Respond / Connect",
      metrics: ["反馈闭环", "家校触达", "服务升级"],
    },
  },
];

export const FEATURED_VIDEOS = [
  {
    id: "knowledge-tool",
    title: "互动式知识理解工具用起来",
    href: "https://v.douyin.com/t9L2hN3pYNA/",
    badge: "Douyin Pick 01",
    summary: "用短视频展示课堂工具如何把知识点变成可视化、可互动、可复用的学习体验。",
    cover: {
      eyebrow: "KNOWLEDGE TOOL",
      headline: "互动式知识理解工具",
      subline: "更直观地理解知识点",
      chips: ["AI 学习", "互动工具", "内容演示"],
    },
  },
  {
    id: "free-english-resources",
    title: "免费英语资源赶紧用起来",
    href: "https://v.douyin.com/nYzhLyIvGDc/",
    badge: "Douyin Pick 02",
    summary: "把英语启蒙和免费资源整理成一条能马上打开的内容，适合作为家长和学生的第一触点。",
    cover: {
      eyebrow: "FREE RESOURCES",
      headline: "免费英语资源",
      subline: "启蒙阶段更容易用起来",
      chips: ["英语启蒙", "学习网站", "资源整理"],
    },
  },
];

export const DOUYIN_PROFILE = {
  name: "@愈见森林",
  subtitle: "持续分享课堂工具、学习资源与应用作品",
  href: "https://www.douyin.com/user/MS4wLjABAAAAxHHFo-1JZJ3GPL_HYbgUo6X7hN5jWrk5wJUYl42rgW0",
  stats: ["抖音主页直达", "继续查看更多内容", "视频与主页双入口"],
};
